language: python
python:
- '2.7'
env:
- TOX_ENV=docs
- TOX_ENV=flake8
- TOX_ENV=py27
- TOX_ENV=py26
install:
- pip install tox==1.6.1
script:
- tox -e $TOX_ENV
deploy:
  provider: pypi
  server: https://pypi.python.org/pypi
  on:
    branch: pypi-release
    condition: $TOX_ENV = py27
  user:
    secure: cfKhNx5vQwXiBA1dn3Ylep0dlzsPmVytxjDTxJckuWuIqM2AX1Vwn6He1Cr++1HvabvPd2tIo2TsaEFMlwhF9R57J57tMirFAt2IdHMN2mcCt+J4A1Bp9V1BpbfFpHzs3K+c+0Y+I3QxrFYVMCV/oopDNL8ehC6RCEyo/dJ5tpc=
  password:
    secure: m16MXLLITVIxTUGxFKI3ZL9SeWlL0fVvt5uAN1Jukwpns6vLVTu3XHfr8JAb2S2dU0QlNnIww6pzKPMR0AlAJ54qG245t42jW7oE5ae5rD5H27R4qhSddRB9nwWKz9kGdDUCps9+awiwR0vobJWg9nJN1rJexGX8CjwJcST/GUM=
after_deploy:
- git clone https://github.com/cloudify-cosmo/travis-utils.git
- python travis-utils/validate_pypi.py -v || exit 1
notifications:
  flowdock: 1f4ec6febcf1ac9b35ae6c1f0049471f
